import pandas as pd

def get_numerical_cols(df):
    """Extract and return the numerical columns of the passed in pandas DataFrame."""
    df_numerical_cols = df.select_dtypes(include="number") # Generated by ChatGPT 5 on 9/28/25 at 7:09 pm
    return df_numerical_cols

def detect_outliers_extreme_vals(df):
    """Detect outliers/extreme values by computing a modified z_score and counting the number of values exceeding 3.5 in magnitude."""
    print("Number of outliers per column:")
    df_numerical_cols = get_numerical_cols(df)
    for col_name, col in df_numerical_cols.items():
        median = col.median()
        mad = (col - col.mean()).abs().mean() # Generated by ChatGPT 5 on 9/28/25 at 8:51 PM
        modified_z_score = 0.6745 * (col - median)/mad
        outliers = modified_z_score[abs(modified_z_score) >= 3.5]
        num_outliers = outliers.size
        print(col_name + ": " + str(num_outliers))

def detect_duplicated_rows(df):
    """Detect duplicated rows."""
    num_duplicated_rows = df.duplicated().sum() # Modified version of code was taken from aipi510-fall25/starters/exploratory_data_analysis.ipynb 
    print("Number of duplicated rows in the data:", num_duplicated_rows)