import pandas as pd

def get_numerical_cols(df):
    """Extract and return the numerical columns of the passed in pandas DataFrame."""
    df_numerical_cols = df.select_dtypes(include="number") # Generated by ChatGPT 5 at 7:09 pm
    return df_numerical_cols

def report_central_tendency_measures(df):
    """Report the central tendency measures (mean, median, mode) for each of the numerical variables."""
    print("Central Tendency Measures:")
    df_numerical_cols = get_numerical_cols(df)
    print("Mean:")
    print(df_numerical_cols.mean().to_string())
    print("\n")
    print("Median:")
    print(df_numerical_cols.median().to_string())
    print("\n")
    print("Mode:")
    print(df_numerical_cols.mode().to_string())

def report_measures_of_dispersion(df):
    """Report the measures of dispersion (range, variance, standard deviation) for each of the numerical variables."""
    print("Measures of Dispersion:")
    df_numerical_cols = get_numerical_cols(df)
    print("Range:")
    print((df_numerical_cols.max() - df_numerical_cols.min()).to_string())
    print("\n")
    print("Variance:")
    print(df_numerical_cols.var().to_string())
    print("\n")
    print("Standard Deviation:")
    print(df_numerical_cols.std().to_string())

def describe_distribution(df):
    """Describe the distribution of the numeric columns of the passed in pandas DataFrame."""
    print("Distribution Descriptions:")
    df_numerical_cols = get_numerical_cols(df)
    skewness = df_numerical_cols.skew()
    num_fairly_sym = 0
    num_moderate_skew_neg = 0
    num_moderate_skew_pos = 0
    num_high_skew_neg = 0
    num_high_skew_pos = 0

    for col_name, col in skewness.items(): # Generated by ChatGPT 5 at 7:52 pm
        if col >= -0.5 and col <= 0.5:
            print(col_name + ": Fairly symmetric.")
            num_fairly_sym += 1
        elif abs(col) >= 0.5 and abs(col) <= 1.0:
            if(col < 0):
                print(col_name + ": Moderately skewed in the negative direction.")
                num_moderate_skew_neg += 1
            else:
                print(col_name + ": Moderately skewed in the positive direction.")
                num_moderate_skew_pos += 1
        else:
            if(col < 0):
                print(col_name + ": Highly skewed in the negative direction.")
                num_high_skew_neg += 1
            else:
                print(col_name + ": Highly skewed in the positive direction.")
                num_high_skew_pos += 1
    
    print("\n")
    print("# Fairly Symmetric:", num_fairly_sym)
    print("# Moderate Skew (Negative):", num_moderate_skew_neg)
    print("# Moderate Skew (Positive):", num_moderate_skew_pos)
    print("# High Skew (Negative):", num_high_skew_neg)
    print("# High Skew (Positive):", num_high_skew_pos)