import pandas as pd
from sklearn.preprocessing import OneHotEncoder

def get_numerical_cols(df):
    """Extract and return the numerical columns of the passed in pandas DataFrame."""
    df_numerical_cols = df.select_dtypes(include="number") # Generated by ChatGPT 5 on 9/28/25 at 7:09 pm
    return df_numerical_cols

def get_categorical_cols(df):
    """Extract and return the categorical columns of the passed in pandas DataFrame."""
    df_categorical_cols = df.select_dtypes(include=["object", "category", "bool"]) # include= array generated by ChatGPT 5 on 9/30/25 at 2:57 am, later modified to include bool
    return df_categorical_cols

def encode_categorical_cols(df):
    """One-hot encode the categorical cols, concatenate with the numerical cols, and return the resulting DataFrame."""
    ohe = OneHotEncoder(sparse_output=False)
    df_numerical_cols = get_numerical_cols(df)
    df_categorical_cols = get_categorical_cols(df)
    encoded_categorical_cols = pd.DataFrame(ohe.fit_transform(df_categorical_cols), columns=ohe.get_feature_names_out(df_categorical_cols.columns), index=df.index) # columns and index parameters generated by ChatGPT 5 on 9/30/25 at 4:43 am
    return pd.concat(objs=[df_numerical_cols, encoded_categorical_cols], axis=1)