import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

def get_numerical_cols(df):
    """Extract and return the numerical columns of the passed in pandas DataFrame."""
    df_numerical_cols = df.select_dtypes(include="number") # Generated by ChatGPT 5 on 9/28/25 at 7:09 pm
    return df_numerical_cols

def get_corr_matrix(df):
    corr_matrix = df.corr()
    return corr_matrix